[package]
name = "polykill"
version = "0.3.2"
edition = "2021"
license = "MIT"
authors = ["Bryn Deering"]
description = "Lightweight command line utility for removing dependencies and build artifacts from unused projects."
readme = "README.md"
homepage = "https://github.com/Bdeering1/polykill#readme"
repository = "https://github.com/Bdeering1/polykill"
keywords = ["cli", "filesystem", "tools"]
categories = ["command-line-utilities", "development tools", "filesystem"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.2.0"
clap = { version = "4.2.2", features = ["derive"]}
console = "0.15.5"
